### ISSUE TITLE
No such file or directory: 'merged_prompt_data.json'

### ISSUE THREAD

**Issue by Rhymeheart** [GuanlinLee/ART#4]
I want to generate my own datasets for llm by running craft_llm_dataset.py. But it warned me that there's no  such file or directory: 'merged_prompt_data.json'. Could u please provide it for me?

**Comment by GuanlinLee** [comment]
It should be the Meta Data, which can be found in our huggingface page.

There are some inconsistencies in file names. We will try to fix them.
